# Generated by Django 5.0.6 on 2024-05-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=10)),
                ('text_result', models.TextField()),
                ('speaker_text_result', models.TextField()),
                ('utterance_count', models.IntegerField()),
                ('sentiment_value', models.FloatField()),
            ],
        ),
    ]
