# Generated by Django 5.0.6 on 2024-06-26 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_support_app', '0002_rename_speaker_text_result_data_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
